library(RODBC)

ch <- odbcConnect("SystemHData")


sqlTables(ch)

sqlQ1<-sqlQuery(ch, paste('SELECT TOP 1000 [SERVICEITEMGROUPID]
      ,[DESCRIPTION]
      ,[IMAGEICON]
      ,[ACTIVEINDIC]
      ,[CAPTUREDDATE]
      ,[CAPTUREDUSERID]
      ,[AMENDEDDATE]
      ,[AMENDEDUSERID]
      ,[DISPLAYORDER]
      ,[BUTTONCOLOUR]
  FROM [iLaundry].[dbo].[SERVICEITEMGROUP]'))

myServiceAnalysisQLString <- 'SELECT SALESDOCUMENT.SALESDOCUMENTID as SalesDocumentID, SALESDOCUMENTLINE.SERVICEITEMTYPEID as ServiceType, 
                SERVICETYPE.DESCRIPTION AS ServiceDescription,
		SALESDOCUMENT.DOCUMENTNO as Invoice, CUSTOMERRETAIL.CUSTOMERNO AS Customer,
		SALESDOCUMENT.DOCUMENTDATE as CompletedDate, SALESDOCUMENT.DOCUMENTDATE as CompletedDate, CUSTOMERRETAIL.CUSTOMERTITLEID as CustomerID, 
		iif(CUSTOMERRETAIL.CUSTOMERTITLEID =8,\'\',CUSTOMERTITLE.DESCRIPTION)+\' \'+  CUSTOMERRETAIL.FIRSTNAME+\' \'+CUSTOMERRETAIL.SURNAME as Customer,  
		CUSTOMERRETAIL.MOBILENUMBER as Mobile, SALESDOCUMENTLINE.LINETOTAL as Value
FROM     CUSTOMERRETAIL INNER JOIN
                  SALESDOCUMENT ON CUSTOMERRETAIL.CUSTOMERRETAILID = SALESDOCUMENT.CUSTOMERRETAILID INNER JOIN
                  CUSTOMERTITLE ON CUSTOMERRETAIL.CUSTOMERTITLEID = CUSTOMERTITLE.CUSTOMERTITLEID INNER JOIN
                  SALESDOCUMENTLINE ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTLINE.SALESDOCUMENTID INNER JOIN
				  SERVICEITEMTYPE ON SALESDOCUMENTLINE.SERVICEITEMTYPEID = SERVICEITEMTYPE.SERVICEITEMTYPEID INNER JOIN
				  SERVICETYPE ON SERVICEITEMTYPE.SERVICETYPEID = SERVICETYPE.SERVICETYPEID
WHERE  (SALESDOCUMENT.DOCUMENTTYPEID = 2) AND (SALESDOCUMENT.DOCUMENTSTATUSID = 10) AND (SALESDOCUMENTLINE.SERVICEITEMTYPEID IS NOT NULL) AND 
                  (SALESDOCUMENT.DOCUMENTDATE > CONVERT(DATETIME, \'2013-08-01 00:00:00\', 102)) AND (SALESDOCUMENT.DOCUMENTDATE <= CONVERT(DATETIME, \'2020-08-13 00:00:00\', 102))
GROUP BY SALESDOCUMENT.SALESDOCUMENTID, SALESDOCUMENTLINE.SERVICEITEMTYPEID, SALESDOCUMENT.DOCUMENTNO, SALESDOCUMENT.DOCUMENTDATE, CUSTOMERRETAIL.CUSTOMERTITLEID,
		CUSTOMERTITLE.DESCRIPTION, CUSTOMERRETAIL.FIRSTNAME, CUSTOMERRETAIL.SURNAME, CUSTOMERRETAIL.MOBILENUMBER,
		SALESDOCUMENTLINE.LINETOTAL, SERVICETYPE.DESCRIPTION, CUSTOMERRETAIL.CUSTOMERNO'


sqlQ2 <- sqlQuery(ch, paste(myServiceAnalysisQLString))
write.csv(file="c:/doc/Levingers/myRServiceAnalysis.csv", x=sqlQ2)

odbcClose(ch)
