# Run this script whenever the iLaundry database on this computer 
# has been updated ie about once a month.
# This file creates two summaries of the iLaundry db:
# salesFrame and productFrame and saves them in sql server.

ch <- odbcConnect("SystemHData")
chShop <- odbcConnect("shopData")
  
SqlProductString <- 'SELECT SALESDOCUMENT.SALESDOCUMENTID as SalesDocumentID,
                        PRODUCTTYPE.DESCRIPTION AS ProductType,
        		PRODUCT.DESCRIPTION AS Product,
                        SALESDOCUMENTLINE.PRODUCTID as ProductTypeID, 
                        SALESDOCUMENT.DOCUMENTDATE as SalesDate,
                        SALESDOCUMENT.DOCUMENTNO as Invoice,
                        SALESDOCUMENTLINE.LINETOTAL as Value
                FROM     CUSTOMERRETAIL INNER JOIN
                                SALESDOCUMENT ON CUSTOMERRETAIL.CUSTOMERRETAILID = SALESDOCUMENT.CUSTOMERRETAILID INNER JOIN
				SALESDOCUMENTAUDIT ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTAUDIT.SALESDOCUMENTID INNER JOIN
                                CUSTOMERTITLE ON CUSTOMERRETAIL.CUSTOMERTITLEID = CUSTOMERTITLE.CUSTOMERTITLEID INNER JOIN
                                SALESDOCUMENTLINE ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTLINE.SALESDOCUMENTID INNER JOIN
		                PRODUCT ON PRODUCT.PRODUCTID = SALESDOCUMENTLINE.PRODUCTID INNER JOIN
		                PRODUCTTYPE ON PRODUCTTYPE.PRODUCTTYPEID = PRODUCT.PRODUCTTYPEID
        WHERE  (SALESDOCUMENT.DOCUMENTTYPEID = 1) AND 
				SALESDOCUMENT.CUSTOMERRETAILID = 12761
        GROUP BY SALESDOCUMENT.SALESDOCUMENTID,
                        SALESDOCUMENTLINE.PRODUCTID, 
                        SALESDOCUMENT.DOCUMENTNO, 
                        SALESDOCUMENT.DOCUMENTDATE, 
         				SALESDOCUMENTLINE.LINETOTAL,
						PRODUCT.DESCRIPTION,
						PRODUCTTYPE.DESCRIPTION'


#This string is to produce a query for SERVICE rendered of ANY type...
        SalesOrdersSQLstring <-'use iLaundry SELECT SALESDOCUMENT.SALESDOCUMENTID as SalesDocumentID, 
                SALESDOCUMENTLINE.SERVICEITEMTYPEID as ServiceType,
                SERVICETYPE.DESCRIPTION AS ServiceDescription,
                SERVICEITEMTYPE.DESCRIPTION AS ServiceItem,
                SALESDOCUMENT.DOCUMENTNO as Invoice, 
                CUSTOMERRETAIL.CUSTOMERNO AS CustomerNo,
                SALESDOCUMENT.DOCUMENTDATE as SalesDate,  
                CUSTOMERRETAIL.CUSTOMERTITLEID as CustomerID, 
                iif(CUSTOMERRETAIL.CUSTOMERTITLEID =8,\'\',CUSTOMERTITLE.DESCRIPTION)+\' \'+  CUSTOMERRETAIL.FIRSTNAME+\' \'+CUSTOMERRETAIL.SURNAME as Customer,  
                CUSTOMERRETAIL.MOBILENUMBER as Mobile, 
                SALESDOCUMENTLINE.LINETOTAL as Value
                into #myTempTable
        FROM     CUSTOMERRETAIL INNER JOIN
                SALESDOCUMENT ON CUSTOMERRETAIL.CUSTOMERRETAILID = SALESDOCUMENT.CUSTOMERRETAILID INNER JOIN
                SALESDOCUMENTAUDIT ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTAUDIT.SALESDOCUMENTID INNER JOIN
                CUSTOMERTITLE ON CUSTOMERRETAIL.CUSTOMERTITLEID = CUSTOMERTITLE.CUSTOMERTITLEID INNER JOIN
                SALESDOCUMENTLINE ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTLINE.SALESDOCUMENTID INNER JOIN
                SERVICEITEMTYPE ON SALESDOCUMENTLINE.SERVICEITEMTYPEID = SERVICEITEMTYPE.SERVICEITEMTYPEID INNER JOIN
                SERVICETYPE ON SERVICEITEMTYPE.SERVICETYPEID = SERVICETYPE.SERVICETYPEID
                WHERE  (SALESDOCUMENT.DOCUMENTTYPEID = 1) AND  
                (SALESDOCUMENTLINE.SERVICEITEMTYPEID IS NOT NULL)
        GROUP BY SALESDOCUMENT.SALESDOCUMENTID,
                SALESDOCUMENTLINE.SERVICEITEMTYPEID, 
                SALESDOCUMENT.DOCUMENTNO, 
                SALESDOCUMENT.DOCUMENTDATE, 
                CUSTOMERRETAIL.CUSTOMERTITLEID,
                CUSTOMERTITLE.DESCRIPTION, 
                CUSTOMERRETAIL.FIRSTNAME, 
                CUSTOMERRETAIL.SURNAME, 
                CUSTOMERRETAIL.MOBILENUMBER,
                SALESDOCUMENTLINE.LINETOTAL, 
                SERVICETYPE.DESCRIPTION, 
                CUSTOMERRETAIL.CUSTOMERNO, 
                SERVICEITEMTYPE.DESCRIPTION'
                
        # This line returns no result, Result is read into MyTempTable        
                sqlQ1 <- sqlQuery(ch, paste(SalesOrdersSQLstring))
        
        # This result reads the result from MyTempTable        
                SalesOrdersSQLstring2 <- 'SELECT *, SUM(Value) OVER(partition by ServiceDescription order by  SalesDate)[Cumulative Sum]
        FROM #myTempTable'
        
        
        SalesOrders<- sqlQuery(ch, paste(SalesOrdersSQLstring2))  
        
        Str3 <- 'SELECT * FROM #myTempTable'
        sqlQ3<- sqlQuery(ch, paste(Str3))
        newlsqlQ3 <- lapply(1:length(sqlQ3[,1]), FUN=replaceItems, Table = sqlQ3)
        salesFrame <- ldply(newlsqlQ3, data.frame)
 



        productFrame <- sqlQuery(ch, paste(SqlProductString))  
        productFrame$SalesDate<-format(as.Date(productFrame$SalesDate),"%Y-%m-%d %H:%M")
        salesFrame$SalesDate<-format(as.Date(salesFrame$SalesDate),"%Y-%m-%d %H:%M")

#         salesFrame$yMon <- as.yearmon(as.Date(salesFrame$SalesDate), "%YM%m")
#         productFrame$yMon <- as.yearmon(as.Date(productFrame$SalesDate), "%YM%m")

        
        productFrame$Type <- "Counter"
        productFrame$Category <- "Product"
        salesFrame$Category <- "Service"
        
                shortsalesFrame <- salesFrame[,c("ServiceDescription","SalesDate","Category", "Value")]
                shortproductFrame <- productFrame[,c("Type","SalesDate","Category", "Value")]
                shortproductFrame<-rename(shortproductFrame, c("Type"="Description"))
                shortsalesFrame<-rename(shortsalesFrame, c("ServiceDescription"="Description"))

        consolidatedFrame <- rbind(shortproductFrame, shortsalesFrame)

        sqlDrop(chShop, "productFrame") 
        sqlSave(chShop, productFrame, append = FALSE,
                colnames = FALSE,rownames = FALSE)

        sqlDrop(chShop, "salesFrame") 
        sqlSave(chShop, salesFrame, append = FALSE,
                colnames = FALSE,rownames = FALSE)

        sqlDrop(chShop, "consolidatedFrame") 
        sqlSave(chShop, consolidatedFrame, append = FALSE,
                colnames = FALSE,rownames = FALSE)


odbcClose(ch)         
odbcClose(chShop)    

#-----------------------------------------------------------------------------------------------------

# SqlProductString <- 'SELECT SALESDOCUMENT.SALESDOCUMENTID as SalesDocumentID,
#                         SYSTEMUSER.FULLNAME as UserName,
#                         SALESDOCUMENTAUDIT.LOGGEDINUSERID as UserID,  
# PRODUCTTYPE.DESCRIPTION AS ProductType,
# PRODUCT.DESCRIPTION AS Product,
# SALESDOCUMENTLINE.PRODUCTID as ProductTypeID, 
# SALESDOCUMENT.DOCUMENTDATE as SalesDate,
# SALESDOCUMENT.DOCUMENTNO as Invoice,
# SALESDOCUMENTLINE.LINETOTAL as Value
# FROM     CUSTOMERRETAIL INNER JOIN
# SALESDOCUMENT ON CUSTOMERRETAIL.CUSTOMERRETAILID = SALESDOCUMENT.CUSTOMERRETAILID INNER JOIN
# SALESDOCUMENTAUDIT ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTAUDIT.SALESDOCUMENTID INNER JOIN
# SYSTEMUSER ON SALESDOCUMENTAUDIT.LOGGEDINUSERID = SYSTEMUSER.SYSTEMUSERID INNER JOIN
# CUSTOMERTITLE ON CUSTOMERRETAIL.CUSTOMERTITLEID = CUSTOMERTITLE.CUSTOMERTITLEID INNER JOIN
# SALESDOCUMENTLINE ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTLINE.SALESDOCUMENTID INNER JOIN
# PRODUCT ON PRODUCT.PRODUCTID = SALESDOCUMENTLINE.PRODUCTID INNER JOIN
# PRODUCTTYPE ON PRODUCTTYPE.PRODUCTTYPEID = PRODUCT.PRODUCTTYPEID
# WHERE  (SALESDOCUMENT.DOCUMENTTYPEID = 1) AND 
# SALESDOCUMENT.CUSTOMERRETAILID = 12761
# GROUP BY SALESDOCUMENT.SALESDOCUMENTID,
# SALESDOCUMENTAUDIT.LOGGEDINUSERID,
# SYSTEMUSER.FULLNAME, 
# SALESDOCUMENTLINE.PRODUCTID, 
# SALESDOCUMENT.DOCUMENTNO, 
# SALESDOCUMENT.DOCUMENTDATE, 
# SALESDOCUMENTLINE.LINETOTAL,
# PRODUCT.DESCRIPTION,
# PRODUCTTYPE.DESCRIPTION'
# 
# 
# #This string is to produce a query for SERVICE rendered of ANY type...
# SalesOrdersSQLstring <-'use iLaundry SELECT SALESDOCUMENT.SALESDOCUMENTID as SalesDocumentID, 
# SALESDOCUMENTLINE.SERVICEITEMTYPEID as ServiceType,
# SYSTEMUSER.FULLNAME as UserName,
# SALESDOCUMENTAUDIT.LOGGEDINUSERID as UserID,  
# SERVICETYPE.DESCRIPTION AS ServiceDescription,
# SERVICEITEMTYPE.DESCRIPTION AS ServiceItem,
# SALESDOCUMENT.DOCUMENTNO as Invoice, 
# CUSTOMERRETAIL.CUSTOMERNO AS CustomerNo,
# SALESDOCUMENT.DOCUMENTDATE as SalesDate,  
# CUSTOMERRETAIL.CUSTOMERTITLEID as CustomerID, 
# iif(CUSTOMERRETAIL.CUSTOMERTITLEID =8,\'\',CUSTOMERTITLE.DESCRIPTION)+\' \'+  CUSTOMERRETAIL.FIRSTNAME+\' \'+CUSTOMERRETAIL.SURNAME as Customer,  
# CUSTOMERRETAIL.MOBILENUMBER as Mobile, 
# SALESDOCUMENTLINE.LINETOTAL as Value
# into #myTempTable
# FROM     CUSTOMERRETAIL INNER JOIN
# SALESDOCUMENT ON CUSTOMERRETAIL.CUSTOMERRETAILID = SALESDOCUMENT.CUSTOMERRETAILID INNER JOIN
# SALESDOCUMENTAUDIT ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTAUDIT.SALESDOCUMENTID INNER JOIN
# SYSTEMUSER ON SALESDOCUMENTAUDIT.LOGGEDINUSERID = SYSTEMUSER.SYSTEMUSERID INNER JOIN
# CUSTOMERTITLE ON CUSTOMERRETAIL.CUSTOMERTITLEID = CUSTOMERTITLE.CUSTOMERTITLEID INNER JOIN
# SALESDOCUMENTLINE ON SALESDOCUMENT.SALESDOCUMENTID = SALESDOCUMENTLINE.SALESDOCUMENTID INNER JOIN
# SERVICEITEMTYPE ON SALESDOCUMENTLINE.SERVICEITEMTYPEID = SERVICEITEMTYPE.SERVICEITEMTYPEID INNER JOIN
# SERVICETYPE ON SERVICEITEMTYPE.SERVICETYPEID = SERVICETYPE.SERVICETYPEID
# WHERE  (SALESDOCUMENT.DOCUMENTTYPEID = 1) AND  
# (SALESDOCUMENTLINE.SERVICEITEMTYPEID IS NOT NULL)
# GROUP BY SALESDOCUMENT.SALESDOCUMENTID,
# SALESDOCUMENTAUDIT.LOGGEDINUSERID,
# SYSTEMUSER.FULLNAME, 
# SALESDOCUMENTLINE.SERVICEITEMTYPEID, 
# SALESDOCUMENT.DOCUMENTNO, 
# SALESDOCUMENT.DOCUMENTDATE, 
# CUSTOMERRETAIL.CUSTOMERTITLEID,
# CUSTOMERTITLE.DESCRIPTION, 
# CUSTOMERRETAIL.FIRSTNAME, 
# CUSTOMERRETAIL.SURNAME, 
# CUSTOMERRETAIL.MOBILENUMBER,
# SALESDOCUMENTLINE.LINETOTAL, 
# SERVICETYPE.DESCRIPTION, 
# CUSTOMERRETAIL.CUSTOMERNO, 
# SERVICEITEMTYPE.DESCRIPTION'
                